name: absence_manager
description: Crewmeister Frontend Coding Challenge
version: 0.0.1
environment:
  sdk: "^3.2.0"
dev_dependencies:
  test: ^1.25.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  build_runner: ^2.1.10
  
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.19.0
  path_provider: ^2.0.15
  share_plus: ^10.0.3

flutter:  
  uses-material-design: true
  assets:  
    - assets/json_files/absences.json    
    - assets/json_files/members.json
